version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: latest
      - node/install-packages:
          cache-path: ~/hack-party/node_modules
          override-ci-command: npm install
      - run: npm run test:unit
workflows:
  node-tests:
    jobs:
      - test
