<template lang="pug">
Reveal
  .slides
    Title
    Slide(class='darkgray')
      img(src='/images/the_verge_headline.png')
      h1 Big News in AI
    Slide(class='darkgray')
      img(src='/images/garth_brooks_question.png')
    Slide(class='darkgray')
      img(src='/images/garth_brooks_question_2.png')
    Slide(class='darkgray')
      img(src='/images/garth_brooks_question_3.png')
    Slide(class='darkgray')
      img(src='/images/garth_brooks_question_4.png')
    VideoSlide(background='/video/robots_take_my_job.mp4')
      h2.title The Robots Are Taking My Job
    Slide
      h2.fragment Solo
      h2.fragment Trivia question
      h2.fragment Multiple choice code generated by ChatGPT
      h2.fragment Contrarians get 2X!
      h1 Game Play
    PlayerBoard
    Slide(class='darkgray')
      h2.text-white Let's go!
    Slide(class='green')
      h2.text-white Which of the following refers to the ability of a person or organism to function at a higher level than would be possible without the use of artificial body parts or other technological enhancements?
    ItemGuess(
      :items='bionic_2'
      :winnerIndex='2'
      question='What is the answer the AI generated?'
      :prize='1'
      headerImage='/images/gameHeader.png'
      denomination=''
      :fragmentItemReveal='true'
    )
    Slide(class='green')
      h2.text-white Which of the following refers to a type of machine learning algorithm that is based on the structure and function of the human brain and is capable of learning from data inputs and making predictions or decisions without being explicitly programmed?
    ItemGuess(
      :items='neural_network_3'
      :winnerIndex='3'
      question='What is the answer the AI generated?'
      :prize='1'
      headerImage='/images/gameHeader.png'
      denomination=''
      :fragmentItemReveal='true'
    )
    Slide(class='green')
      h2.text-white Which of the following refers to the ability of an organism or machine to move from one place to another?
    ItemGuess(
      :items='locomotion_2'
      :winnerIndex='2'
      question='What is the answer the AI generated?'
      :prize='1'
      headerImage='/images/gameHeader.png'
      denomination=''
      :fragmentItemReveal='true'
    )
    Slide(class='green')
      h2.text-white Which of the following is the company that dominates the market for industrial robotics and has the largest market share of all the major players in the industry?
    ItemGuess(
      :items='siemens_3'
      :winnerIndex='3'
      question='What is the answer the AI generated?'
      :prize='1'
      headerImage='/images/gameHeader.png'
      denomination=''
      :fragmentItemReveal='true'
    )
    Slide(class='green')
      h2.text-white Which of the following movies, featuring robots as significant characters, has earned the most money at the box office worldwide?
    ItemGuess(
      :items='dark_of_the_moon_0'
      :winnerIndex='0'
      question='What is the answer the AI generated?'
      :prize='1'
      headerImage='/images/gameHeader.png'
      denomination=''
      :fragmentItemReveal='true'
    )
    Slide(class='green')
      h2.text-white Which of the following is a type of robot that is designed to work alongside humans and is typically characterized by its lightweight construction, ease of programming, and safety features?
    ItemGuess(
      :items='collaborative_3'
      :winnerIndex='3'
      question='What is the answer the AI generated?'
      :prize='1'
      headerImage='/images/gameHeader.png'
      denomination=''
      :fragmentItemReveal='true'
    )
    VideoSlide(background='/video/bossfight.mp4')
      h2.nintendo Boss Fight!!
    Slide(class='darkgray')
      img(src='/images/boss_fight_idea.png')
    Slide
      h2.fragment 3 question showdown
      h2.fragment 2 points per correct answer
      h2.fragment 5 points for last players standing
      h2.fragment 2x if only one player remains!
      h1 Game Play
    KnockoutRound(
      :questions='boss_fight_1'
      :prize='2'
      headerImage='/images/gameHeader.png'
      denomination=''
      :fragmentItemReveal='true'
    )
    PlayerBoard
    VideoSlide(
      background='/video/flight_of_the_conchords.mp4'
      :muted='false'
    )
    PlayerBoard
    Slide(class='green')
      h2.text-white What is the punchline of the joke, "Why couldn't the robot open the juice box?"
    ItemGuess(
      :items='dad_joke_3'
      :winnerIndex='3'
      question='What is the answer the AI generated?'
      :prize='2'
      headerImage='/images/gameHeader.png'
      denomination=''
      :fragmentItemReveal='true'
    )
    Slide(class='green')
      h2.text-white Which of the following is considered one of the most important science fiction novels about robots and artificial intelligence, and is credited with popularizing the term "robotics"?
    ItemGuess(
      :items='books_3'
      :winnerIndex='3'
      question='What is the answer the AI generated?'
      :prize='2'
      headerImage='/images/gameHeader.png'
      denomination=''
      :fragmentItemReveal='true'
    )
    Slide(class='green')
      h2.text-white How many times has Boston Dynamics been sold?
    ItemGuess(
      :items='boston_dynamics_3'
      :winnerIndex='3'
      question='What is the answer the AI generated?'
      :prize='2'
      headerImage='/images/gameHeader.png'
      denomination=''
      :fragmentItemReveal='true'
    )
    Slide(class='green')
      h2.text-white What test do blade runners use to distinguish replicants from humans?
    ItemGuess(
      :items='voight_kampf_1'
      :winnerIndex='1'
      question='What is the answer the AI generated?'
      :prize='2'
      headerImage='/images/gameHeader.png'
      denomination=''
      :fragmentItemReveal='true'
    )
    Slide(class='green')
      h2.text-white What is the name of a droid that was not used in the Star Wars franchise?
    ItemGuess(
      :items='droid_3'
      :winnerIndex='3'
      question='What is the answer the AI generated?'
      :prize='2'
      headerImage='/images/gameHeader.png'
      denomination=''
      :fragmentItemReveal='true'
    )
    Slide(class='green')
      h2.text-white What is the process in which a robot is able to improve its performance on a specific task through repeated practice and experience?
    ItemGuess(
      :items='reinforcement_3'
      :winnerIndex='3'
      question='What is the answer the AI generated?'
      :prize='2'
      headerImage='/images/gameHeader.png'
      denomination=''
      :fragmentItemReveal='true'
    )
    Slide(class='green')
      h2.text-white What is the mission for the robot probe in the movie WALL-E?
    ItemGuess(
      :items='walle_2'
      :winnerIndex='2'
      question='What is the answer the AI generated?'
      :prize='2'
      headerImage='/images/gameHeader.png'
      denomination=''
      :fragmentItemReveal='true'
    )
    VideoSlide(background='/video/bossfight.mp4')
      h2.nintendo Boss Fight!!
    KnockoutRound(
      :questions='boss_fight_2'
      :prize='3'
      :bonus='10'
      headerImage='/images/gameHeader.png'
      denomination=''
      :fragmentItemReveal='true'
    )
    PlayerBoard
    VideoSlide(
      background='/video/robot_jox.mp4'
      :muted='false'
    )
    PlayerBoard
    BackgroundImageSlide(background='/images/robot_take_the_wheel.jpeg')
      h1 Robot take the wheel!
    Slide(class='green')
      h2.text-white What is the robot equivalent of the "five second rule"?
    ItemGuess(
      :items='five_second_rule_3'
      :winnerIndex='3'
      question='What is the answer the AI generated?'
      :prize='3'
      headerImage='/images/gameHeader.png'
      denomination=''
      :fragmentItemReveal='true'
    )
    Slide(class='green')
      h2.text-white What is the "guilty pleasure" TV show for robots?
    ItemGuess(
      :items='hoarders_4'
      :winnerIndex='3'
      question='What is the answer the AI generated?'
      :prize='3'
      headerImage='/images/gameHeader.png'
      denomination=''
      :fragmentItemReveal='true'
    )
    Slide(class='green')
      h2.text-white What is the first robot to be used in a surgical procedure?
    ItemGuess(
      :items='da_vinci_0'
      :winnerIndex='0'
      question='What is the answer the AI generated?'
      :prize='3'
      headerImage='/images/gameHeader.png'
      denomination=''
      :fragmentItemReveal='true'
    )
    Slide(class='green')
      h2.text-white What is the most popular robot pet?
    ItemGuess(
      :items='zoomer_0'
      :winnerIndex='0'
      question='What is the answer the AI generated?'
      :prize='3'
      headerImage='/images/gameHeader.png'
      denomination=''
      :fragmentItemReveal='true'
    )
    Slide(class='green')
      h2.text-white What is the most lovable robot in a film?
    ItemGuess(
      :items='r2d2_0'
      :winnerIndex='0'
      question='What is the answer the AI generated?'
      :prize='3'
      headerImage='/images/gameHeader.png'
      denomination=''
      :fragmentItemReveal='true'
    )
    Slide(class='green')
      h2.text-white What is the most popular robot-related song?
    ItemGuess(
      :items='styx_0'
      :winnerIndex='0'
      question='What is the answer the AI generated?'
      :prize='3'
      headerImage='/images/gameHeader.png'
      denomination=''
      :fragmentItemReveal='true'
    )
    PlayerBoard
    VideoSlide(background='/video/bossfight.mp4')
      h2.nintendo Boss Fight!!
    KnockoutRound(
      :questions='boss_fight_3'
      :prize='5'
      :bonus='20'
      headerImage='/images/gameHeader.png'
      denomination=''
      :fragmentItemReveal='true'
    )
    PlayerBoard
</template>
https://youtu.be/LYQM1NESLsc
<script>
import BackgroundImageSlide from '@/components/base/BackgroundImageSlide.vue'
import Reveal from '@/components/base/Reveal.vue'
import Title from '@/components/base/Title.vue'
import Slide from '@/components/base/Slide.vue'
import VideoSlide from '@/components/base/VideoSlide.vue'
import ActionButton from '@/components/base/ActionButton.vue'
import GameVideo from '@/components/base/GameVideo.vue'

import PlayerBoard from '@/components/Players/PlayerBoard.vue'

import ItemGuess from '@/components/WhichIsWhich/ItemGuess.vue'

import GameContentWithSidebar from '@/components/base/GameContentWithSidebar.vue'

import KnockoutRound from '@/components/KnockoutRound/KnockoutRound.vue'

export default {
  name: 'Home',
  components: {
    PlayerBoard,
    Title,
    Slide,
    Reveal,
    BackgroundImageSlide,
    VideoSlide,
    ActionButton,
    GameVideo,
    ItemGuess,
    GameContentWithSidebar,
    KnockoutRound
  },
  data () {
    return {
      bionic_2: [
        { name: 'Robotic', emoji: '🤖', value: 'the AI generated answer' },
        { name: 'Cybernetic', emoji: '💻', value: 'the AI generated answer' },
        { name: 'Bionic', emoji: '🦾', value: 'the AI generated answer' },
        { name: 'Mechanical', emoji: '🧲', value: 'the AI generated answer' }
      ],
      neural_network_3: [
        { name: 'Decision tree', emoji: '🌳', value: 'the AI generated answer' },
        { name: 'Random forest', emoji: '🌲', value: 'the AI generated answer' },
        { name: 'Support vector machine', emoji: '📈', value: 'the AI generated answer' },
        { name: 'Neural network', emoji: '🧠', value: 'the AI generated answer' }
      ],
      locomotion_2: [
        { name: 'Reproduction', emoji: '🐛', value: 'the AI generated answer' },
        { name: 'Photosynthesis', emoji: '🌱', value: 'the AI generated answer' },
        { name: 'Locomotion', emoji: '🚶‍♂️', value: 'the AI generated answer' },
        { name: 'Metabolism', emoji: '🧬', value: 'the AI generated answer' }
      ],
      siemens_3: [
        { name: 'ABB', emoji: '🤖', value: 'the AI generated answer' },
        { name: 'Fanuc', emoji: '🤖', value: 'the AI generated answer' },
        { name: 'Yaskawa Electric', emoji: '🤖', value: 'the AI generated answer' },
        { name: 'Siemens', emoji: '🤖', value: 'the AI generated answer' }
      ],
      dark_of_the_moon_0: [
        { name: 'Transformers: Dark of the Moon', emoji: '🤖', value: 'the AI generated answer' },
        { name: 'Transformers: Age of Extinction', emoji: '🤖', value: 'the AI generated answer' },
        { name: 'Transformers: Revenge of the Fallen', emoji: '🤖', value: 'the AI generated answer' },
        { name: 'Transformers: The Last Knight', emoji: '🤖', value: 'the AI generated answer' }
      ],
      collaborative_3: [
        { name: 'Industrial robot', emoji: '🏭', value: 'the AI generated answer' },
        { name: 'Service robot', emoji: '💼', value: 'the AI generated answer' },
        { name: 'Domestic robot', emoji: '🏠', value: 'the AI generated answer' },
        { name: 'Collaborative robot', emoji: '👨‍🦲', value: 'the AI generated answer' }
      ],
      dad_joke_3: [
        { name: "It didn't have hands.", emoji: '🤖', value: 'the AI generated answer' },
        { name: 'It was programmed not to.', emoji: '💻', value: 'the AI generated answer' },
        { name: "It didn't have the strength.", emoji: '💪', value: 'the AI generated answer' },
        { name: 'It was a hardware problem.', emoji: '🔩', value: 'the AI generated answer' }
      ],
      books_3: [
        { name: 'The War of the Worlds', emoji: '🛸', value: 'the AI generated answer' },
        { name: 'Do Androids Dream of Electric Sheep?', emoji: '📱', value: 'the AI generated answer' },
        { name: 'Fahrenheit 451', emoji: '🔥', value: 'the AI generated answer' },
        { name: 'I, Robot', emoji: '👨‍🦲', value: 'the AI generated answer' }
      ],
      boston_dynamics_3: [
        { name: '1', emoji: '1️⃣', value: 'the AI generated answer' },
        { name: '2', emoji: '2️⃣', value: 'the AI generated answer' },
        { name: '3', emoji: '3️⃣', value: 'the AI generated answer' },
        { name: '4', emoji: '4️⃣', value: 'the AI generated answer' }
      ],
      voight_kampf_1: [
        { name: 'Turing test', emoji: '🤖', value: 'the AI generated answer' },
        { name: 'Voight-Kampff test', emoji: '💬', value: 'the AI generated answer' },
        { name: 'Rorschach test', emoji: '🧐', value: 'the AI generated answer' },
        { name: 'Myers-Briggs test', emoji: '🧠', value: 'the AI generated answer' }
      ],
      droid_3: [
        { name: 'R2-D2', emoji: '🤖', value: 'the AI generated answer' },
        { name: 'C-3PO', emoji: '🤖', value: 'the AI generated answer' },
        { name: 'BB-8', emoji: '🤖', value: 'the AI generated answer' },
        { name: 'QT-1', emoji: '🤖', value: 'the AI generated answer' }
      ],
      reinforcement_3: [
        { name: 'Machine learning', emoji: '🤖', value: 'the AI generated answer' },
        { name: 'Artificial intelligence', emoji: '🧠', value: 'the AI generated answer' },
        { name: 'Neural networks', emoji: '🧠', value: 'the AI generated answer' },
        { name: 'Reinforcement learning', emoji: '🧠', value: 'the AI generated answer' }
      ],
      walle_2: [
        { name: "To clean up Earth's waste", emoji: '🌎', value: 'the AI generated answer' },
        { name: 'To explore other planets', emoji: '🪐', value: 'the AI generated answer' },
        { name: 'To find signs of life on Earth', emoji: '🌱', value: 'the AI generated answer' },
        { name: 'To collect data on climate change', emoji: '🌡️', value: 'the AI generated answer' }
      ],
      five_second_rule_3: [
        { name: 'The three second rule', emoji: '⏱️', value: 'the AI generated answer' },
        { name: 'The six second rule', emoji: '⏱️', value: 'the AI generated answer' },
        { name: 'The two second rule', emoji: '⏱️', value: 'the AI generated answer' },
        { name: 'The four second rule', emoji: '⏱️', value: 'the AI generated answer' }
      ],
      hoarders_4: [
        { name: 'Robot Housewives of Silicon Valley', emoji: '📺', value: 'the AI generated answer' },
        { name: 'Robot Bachelor in Paradise', emoji: '📺', value: 'the AI generated answer' },
        { name: 'Robot Chopped', emoji: '📺', value: 'the AI generated answer' },
        { name: 'Robot Hoarders', emoji: '📺', value: 'the AI generated answer' }
      ],
      da_vinci_0: [
        { name: 'da Vinci surgical robot', emoji: '🤖', value: 'the AI generated answer' },
        { name: 'Titan medical robot', emoji: '💉', value: 'the AI generated answer' },
        { name: 'Zeus surgical robot', emoji: '🏥', value: 'the AI generated answer' },
        { name: 'Robodoc surgical robot', emoji: '🔬', value: 'the AI generated answer' }
      ],
      zoomer_0: [
        { name: 'Zoomer', emoji: '🐕', value: 'the AI generated answer' },
        { name: 'FurReal Friends', emoji: '🐱', value: 'the AI generated answer' },
        { name: 'Cozmo', emoji: '🤖', value: 'the AI generated answer' },
        { name: 'Robo Alive', emoji: '🐇', value: 'the AI generated answer' }
      ],
      r2d2_0: [
        { name: 'R2-D2', emoji: '🤖', value: 'the AI generated answer' },
        { name: 'Wall-E', emoji: '🚀', value: 'the AI generated answer' },
        { name: 'Bender', emoji: '🍺', value: 'the AI generated answer' },
        { name: 'RoboCop', emoji: '👮‍♂️', value: 'the AI generated answer' }
      ],
      styx_0: [
        { name: 'Mr. Roboto', emoji: '🎤', value: 'the AI generated answer' },
        { name: 'Robot Rock', emoji: '🤖', value: 'the AI generated answer' },
        { name: 'Robots', emoji: '🎵', value: 'the AI generated answer' },
        { name: 'Robot City', emoji: '🌆', value: 'the AI generated answer' }
      ],
      boss_fight_1: [{
        text: 'What is the name of the famous red-suited Christmas figure?',
        answers: [{ name: 'Rudolph the Red-Nosed Reindeer', emoji: '🦌', value: 'the AI generated answer' }, { name: 'Frosty the Snowman', emoji: '❄️', value: 'the AI generated answer' }, { name: 'Santa Claus', emoji: '🎅', value: 'the AI generated answer' }, { name: 'The Grinch', emoji: '🧑', value: 'the AI generated answer' }],
        winnerIndex: 2
      },
      {
        text: 'In what country did the tradition of the Christmas tree originate?',
        answers: [
          {
            name: 'Germany',
            emoji: '🇩🇪',
            value: 'the AI generated answer'
          },
          {
            name: 'Sweden',
            emoji: '🇸🇪',
            value: 'the AI generated answer'
          },
          {
            name: 'France',
            emoji: '🇫🇷',
            value: 'the AI generated answer'
          },
          {
            name: 'skip',
            emoji: '⏭️',
            value: 'I am skipping this player'
          }
        ],
        winnerIndex: 0
      },
      {
        text: "In the song 'The 12 Days of Christmas,' how many total gifts does the true love give to the singer?",
        answers: [
          {
            name: '36',
            emoji: '🎁🎁🎁',
            value: 'the AI generated answer'
          },
          {
            name: '42',
            emoji: '🎁🎁🎁🎁🎁',
            value: 'the AI generated answer'
          },
          {
            name: '144',
            emoji: '🎁🎁🎁🎁🎁🎁🎁🎁🎁🎁🎁🎁🎁🎁',
            value: 'the AI generated answer'
          },
          {
            name: 'skip',
            emoji: '⏭️',
            value: 'I am skipping this player'
          }
        ],
        winnerIndex: 2
      }
      ],
      boss_fight_2: [{
        text: 'What is the scientific name for the species of deer that includes reindeer?',
        answers: [{ name: 'Odocoileus virginianus', emoji: '🌲', value: 'the AI generated answer' }, { name: 'Rangifer tarandus', emoji: '❄️', value: 'the AI generated answer' }, { name: 'Ovis aries', emoji: '🐏', value: 'the AI generated answer' }],
        winnerIndex: 1
      },
      {
        text: 'What is the name of the condition in which reindeer lose their fur?',
        answers: [
          {
            name: 'Alopecia',
            emoji: '🐇',
            value: 'the AI generated answer'
          },
          {
            name: 'Hypothermia',
            emoji: '❄️',
            value: 'the AI generated answer'
          },
          {
            name: 'Ecdysis',
            emoji: '🐛',
            value: 'the AI generated answer'
          },
          {
            name: 'skip',
            emoji: '⏭️',
            value: 'I am skipping this player'
          }
        ],
        winnerIndex: 2
      },
      {
        text: 'What is the name of the hollow hair that insulates reindeer against the cold?',
        answers: [
          {
            name: 'Down',
            emoji: '🦆',
            value: 'the AI generated answer'
          },
          {
            name: 'Guard hairs',
            emoji: '🐻',
            value: 'the AI generated answer'
          },
          {
            name: 'Underfur',
            emoji: '🐿',
            value: 'the AI generated answer'
          },
          {
            name: 'skip',
            emoji: '⏭️',
            value: 'I am skipping this player'
          }
        ],
        winnerIndex: 2
      }
      ],
      boss_fight_3: [{
        text: 'Which of these carols was originally a poem written by Clement Clarke Moore?',
        answers: [{ name: 'Hark! The Herald Angels Sing', emoji: '🎄', value: 'the AI generated answer' }, { name: 'Jingle Bells', emoji: '🎅', value: 'the AI generated answer' }, { name: 'The Night Before Christmas', emoji: '🎁', value: 'the AI generated answer' }],
        winnerIndex: 2
      },
      {
        text: 'Which of these carols was originally a hymn written by Charles Wesley?',
        answers: [
          {
            name: 'O Come, All Ye Faithful',
            emoji: '🎁',
            value: 'the AI generated answer'
          },
          {
            name: 'We Wish You a Merry Christmas',
            emoji: '🎄',
            value: 'the AI generated answer'
          },
          {
            name: 'Silent Night',
            emoji: '🎅',
            value: 'the AI generated answer'
          },
          {
            name: 'skip',
            emoji: '⏭️',
            value: 'I am skipping this player'
          }
        ],
        winnerIndex: 0
      },
      {
        text: 'Which of these carols was originally a 16th century English folk song?',
        answers: [
          {
            name: 'Deck the Halls',
            emoji: '🎄',
            value: 'the AI generated answer'
          },
          {
            name: 'O Little Town of Bethlehem',
            emoji: '🎅',
            value: 'the AI generated answer'
          },
          {
            name: 'The Twelve Days of Christmas',
            emoji: '🎁',
            value: 'the AI generated answer'
          },
          {
            name: 'skip',
            emoji: '⏭️',
            value: 'I am skipping this player'
          }
        ],
        winnerIndex: 2
      }
      ]
    }
  }
}
</script>

<style lang='scss'>
@import url('https://fonts.googleapis.com/css2?family=Major+Mono+Display&family=Press+Start+2P&display=swap');

.nintendo {
  font-family: 'Press Start 2P', cursive !important;
  @apply mt-72 text-9xl text-white #{!important};
}

.title {
  font-family: 'Major Mono Display', monospace !important;
  @apply mt-32 text-7xl skew-y-12 text-white #{!important};
}

html {
  font-size: 36px;
}
</style>
