<template lang="pug">
Reveal
  .slides
    Title
    Slide(class='darkgray')
      img(src='/images/trump_announcement.jpeg')
    VideoSlide(
      background='/video/trump_announcement.mp4'
      :muted='false'
    )
    VideoSlide(
      background='/video/newsmax_reaction.mp4'
      :muted='false'
    )
    Slide(class='darkgray')
      img(src='/images/nft_sells_out.png')
    BackgroundImageSlide(background='/images/senate_gop.png')
    BackgroundImageSlide(background='/images/stable_diffusion.png')
    VideoSlide(background='/video/trump_announcement.mp4')
      h2.title Scam or Fake?
    Slide
      h2.fragment Solo
      h2.fragment You will be presented with an image
      h2.fragment You guess if it is from Trump's NFT collection...
      h2.fragment ...or generated by an AI.
      h2.fragment Equal number of each in the game ordered randomly
      h2.fragment Rando resizing - dimensions are not an indicator
      h2.fragment Contrarians get 2X!
      h1 Game Play
    PlayerBoard
    GameContentWithSidebar
      template(v-slot:content)
        img.fragment(src='/images/nft_superman.avif')
    ItemGuess(
      :items='scam_or_fake'
      :winnerIndex='0'
      denomination=''
      headerImage='/images/nft_superman.avif'
      :prize='1'
    )
    GameContentWithSidebar
      template(v-slot:content)
        img.fragment(src='/images/ai_doctor_who.png')
    ItemGuess(
      :items='scam_or_fake'
      :winnerIndex='1'
      denomination=''
      headerImage='/images/ai_doctor_who.png'
      :prize='1'
    )
    GameContentWithSidebar
      template(v-slot:content)
        img.fragment(src='/images/ai_eastwood.png')
    ItemGuess(
      :items='scam_or_fake'
      :winnerIndex='1'
      denomination=''
      headerImage='/images/ai_eastwood.png'
      :prize='1'
    )
    GameContentWithSidebar
      template(v-slot:content)
        img.fragment(src='/images/nft_rushmore.avif')
    ItemGuess(
      :items='scam_or_fake'
      :winnerIndex='0'
      denomination=''
      headerImage='/images/nft_rushmore.avif'
      :prize='1'
    )
    GameContentWithSidebar
      template(v-slot:content)
        img.fragment(src='/images/ai_stylized.png')
    ItemGuess(
      :items='scam_or_fake'
      :winnerIndex='1'
      denomination=''
      headerImage='/images/ai_stylized.png'
      :prize='1'
    )
    GameContentWithSidebar
      template(v-slot:content)
        img.fragment(src='/images/ai_hulk.png')
    ItemGuess(
      :items='scam_or_fake'
      :winnerIndex='1'
      denomination=''
      headerImage='/images/ai_hulk.png'
      :prize='1'
    )
    VideoSlide(background='/video/bossfight.mp4')
      h2.text-white.text-9xl.nintendo(style='margin-top: 24rem;') Boss Fight!!
    VideoSlide(background='/video/john_goblikon_christmas_cut.mp4')
    Slide(class='green')
      h2.text-white There are over 50 Santas on Cameo!
    CameoPriceIsRightRound(
      celebrity='Magical Santa Claus'
      hint1='Bills himself as the Official Santa for the Governor of Arkansas'
      hint2='Also claims to be in the Santa Hall of Fame'
      hint3='Definitely a competitive bearder'
      video='/video/magical_santa.mp4'
      image='https://d31wcbk3iidrjq.cloudfront.net/9HNS-zFIL_avatar-X_JP91qG4.jpg'
      :price='100'
      :prize='3'
    )
    PlayerBoard
    VideoSlide(
      background='/video/snl_trump_nfts.mp4'
      :muted='false'
    )
    PlayerBoard
    GameContentWithSidebar
      template(v-slot:content)
        img.fragment(src='/images/nft_golf.avif')
    ItemGuess(
      :items='scam_or_fake'
      :winnerIndex='0'
      denomination=''
      headerImage='/images/nft_golf.avif'
      :prize='2'
    )
    GameContentWithSidebar
      template(v-slot:content)
        img.fragment(src='/images/nft_wailing_wall.avif')
    ItemGuess(
      :items='scam_or_fake'
      :winnerIndex='0'
      denomination=''
      headerImage='/images/nft_wailing_wall.avif'
      :prize='2'
    )
    GameContentWithSidebar
      template(v-slot:content)
        img.fragment(src='/images/ai_captain_america.png')
    ItemGuess(
      :items='scam_or_fake'
      :winnerIndex='1'
      denomination=''
      headerImage='/images/ai_captain_america.png'
      :prize='2'
    )
    GameContentWithSidebar
      template(v-slot:content)
        img.fragment(src='/images/ai_god.png')
    ItemGuess(
      :items='scam_or_fake'
      :winnerIndex='1'
      denomination=''
      headerImage='/images/ai_god.png'
      :prize='2'
    )
    GameContentWithSidebar
      template(v-slot:content)
        img.fragment(src='/images/nft_vanilla.avif')
    ItemGuess(
      :items='scam_or_fake'
      :winnerIndex='0'
      denomination=''
      headerImage='/images/nft_vanilla.avif'
      :prize='2'
    )
    GameContentWithSidebar
      template(v-slot:content)
        img.fragment(src='/images/ai_angel.png')
    ItemGuess(
      :items='scam_or_fake'
      :winnerIndex='1'
      denomination=''
      headerImage='/images/ai_angel.png'
      :prize='2'
    )
    VideoSlide(background='/video/bossfight.mp4')
      h2.text-white.text-9xl.nintendo(style='margin-top: 24rem;') Boss Fight!!
    CameoPriceIsRightRound(
      celebrity='Santa Claus Mexico'
      hint1='Worst rated Santa on Cameo with 1 star'
      hint2='As Santas go, this is not maximum effort'
      hint3='Only one example video'
      video='/video/santa_mexico.mp4'
      image='https://d31wcbk3iidrjq.cloudfront.net/ZgA7Gp20m_avatar-Kfbvggms0.jpg'
      :price='35'
      :prize='5'
    )
    PlayerBoard
    VideoSlide(
      background='/video/stab_into_christmas.mp4'
      :muted='false'
    )
    PlayerBoard
    GameContentWithSidebar
      template(v-slot:content)
        img.fragment(src='/images/nft_baseball.avif')
    ItemGuess(
      :items='scam_or_fake'
      :winnerIndex='0'
      denomination=''
      headerImage='/images/nft_baseball.avif'
      :prize='3'
    )
    GameContentWithSidebar
      template(v-slot:content)
        img.fragment(src='/images/nft_jetpack.avif')
    ItemGuess(
      :items='scam_or_fake'
      :winnerIndex='0'
      denomination=''
      headerImage='/images/nft_jetpack.avif'
      :prize='3'
    )
    GameContentWithSidebar
      template(v-slot:content)
        img.fragment(src='/images/ai_witchy.png')
    ItemGuess(
      :items='scam_or_fake'
      :winnerIndex='1'
      denomination=''
      headerImage='/images/ai_witchy.png'
      :prize='3'
    )
    GameContentWithSidebar
      template(v-slot:content)
        img.fragment(src='/images/nft_elephant.avif')
    ItemGuess(
      :items='scam_or_fake'
      :winnerIndex='0'
      denomination=''
      headerImage='/images/nft_elephant.avif'
      :prize='3'
    )
    GameContentWithSidebar
      template(v-slot:content)
        img.fragment(src='/images/ai_lincoln.png')
    ItemGuess(
      :items='scam_or_fake'
      :winnerIndex='1'
      denomination=''
      headerImage='='
      :prize='3'
    )
    GameContentWithSidebar
      template(v-slot:content)
        img.fragment(src='/images/nft_welder.avif')
    ItemGuess(
      :items='scam_or_fake'
      :winnerIndex='0'
      denomination=''
      headerImage='/images/nft_welder.avif'
      :prize='3'
    )
    PlayerBoard
    VideoSlide(background='/video/bossfight.mp4')
      h2.text-white.text-9xl.nintendo(style='margin-top: 24rem;') Boss Fight!!
    CameoPriceIsRightRound(
      celebrity='The Stripping Santa'
      hint1='Five star reviewed Santa'
      hint2='Definitely higher production value than most Santas'
      hint3='There is a bit of a twist'
      video='/video/stripping_santa.mp4'
      image='https://d31wcbk3iidrjq.cloudfront.net/YyAl1YhEu_avatar-cIsEPkNt3.jpg'
      :price='59'
      :prize='10'
    )
    PlayerBoard
</template>

<script>
import BackgroundImageSlide from '@/components/base/BackgroundImageSlide.vue'
import Reveal from '@/components/base/Reveal.vue'
import Title from '@/components/base/Title.vue'
import Slide from '@/components/base/Slide.vue'
import VideoSlide from '@/components/base/VideoSlide.vue'
import ActionButton from '@/components/base/ActionButton.vue'
import GameVideo from '@/components/base/GameVideo.vue'

import PlayerBoard from '@/components/Players/PlayerBoard.vue'

import GameContentWithSidebar from '@/components/base/GameContentWithSidebar.vue'
import ItemGuess from '@/components/WhichIsWhich/ItemGuess.vue'
import CameoPriceIsRightRound from '@/components/CameoPriceIsRight/CameoPriceIsRightRound.vue'

export default {
  name: 'Home',
  components: {
    PlayerBoard,
    Title,
    Slide,
    Reveal,
    BackgroundImageSlide,
    VideoSlide,
    ActionButton,
    GameVideo,
    GameContentWithSidebar,
    ItemGuess,
    CameoPriceIsRightRound
  },
  data () {
    return {
      scam_or_fake: [
        { name: 'Scam', emoji: '🍑️', value: ' the image' },
        { name: 'Fake', emoji: '🤖️', value: ' the image' }
      ]
    }
  }
}
</script>

<style lang='scss'>
@import url('https://fonts.googleapis.com/css2?family=Diplomata+SC&family=Press+Start+2P&display=swap');

.nintendo {
  font-family: 'Press Start 2P', cursive !important;
  @apply mt-72 text-9xl text-white #{!important};
}

.title {
  font-family: 'Diplomata SC', cursive !important;
  @apply mt-72 text-9xl skew-y-12 text-white #{!important};
}

html {
  font-size: 36px;
}
</style>
