<template lang="pug">
Reveal
  .slides
    Title
    BackgroundImageSlide(
      background='/images/skynet.gif'
    )
      h1 The machines are taking over
    BackgroundImageSlide(
      background='/images/gan_diagram.webp'
    )
      h1 Generative Adversarial Networks
    BackgroundImageSlide(
      background='/images/dalle.png'
    )
      h1 DALL-E 2
    BackgroundImageSlide(
      background='/images/dalle-mini.png'
    )
      h1 Much less good open source version
    Slide
      h2.fragment Solo
      h2.fragment Give 9 images generated by DALL-E Mini
      h2.fragment Guess the prompt that produced them
      h2.fragment Most specific wins
      h1 Game play
    PlayerBoard
    Slide(class='darkgray')
      h2.text-white Art of the surreal
    GameContentWithSidebar
      template(v-slot:content)
        img(src='/images/a_banana_competing_in_a_steeplchase.png')
      template(v-slot:footer)
        h1.fragment A banana competing in a steeplechase
    ChooseWinner(headerImage='/images/header_for_winner_modal.png')
    GameContentWithSidebar
      template(v-slot:content)
        img(src='/images/a_cat_driving_a_combine_harvesting_fish.png')
      template(v-slot:footer)
        h1.fragment A cat driving a combine harvesting fish
    ChooseWinner(headerImage='/images/header_for_winner_modal.png')
    GameContentWithSidebar
      template(v-slot:content)
        img(src='/images/feral_pigs_throwing_bitcoin_at_each_other_in_an_empty_swimming_pool.png')
      template(v-slot:footer)
        h1.fragment Feral pigs throwing Bitcoin at each other in an empty swimming pool
    ChooseWinner(headerImage='/images/header_for_winner_modal.png')
    GameContentWithSidebar
      template(v-slot:content)
        img(src='/images/a_teenage_mutant_ninja_turtle_delivering_an_oration_to_the_house_of_commons.png')
      template(v-slot:footer)
        h1.fragment A Teenage Mutant Ninja Turtle delivering an oration to the House of Commons
    ChooseWinner(headerImage='/images/header_for_winner_modal.png')
    GameContentWithSidebar
      template(v-slot:content)
        img(src='/images/barney_the_dinosaur_receiving_communion_from_oscar_the_grouch.png')
      template(v-slot:footer)
        h1.fragment Barney the Dinosaur receiving communion from Oscar the Grouch
    ChooseWinner(headerImage='/images/header_for_winner_modal.png')
    GameContentWithSidebar
      template(v-slot:content)
        img(src='/images/punk_rock_band_doing_laundry_in_a_river.png')
      template(v-slot:footer)
        h1.fragment Punk rock band doing laundry in a river
    ChooseWinner(headerImage='/images/header_for_winner_modal.png')
    PlayerBoard
    PlayerBoard
    Slide(class='darkgray')
      h2.text-white West Wing Quotations
    GameContentWithSidebar
      template(v-slot:content)
        img(src='/images/i_drink_from_the_keg_of_glory_bring_me_the_finest_muffins_and_bagels_in_all_the_land.png')
      template(v-slot:footer)
        h1.fragment I drink from the keg of glory. Bring me the finest muffins and bagels in all the land
    ChooseWinner(headerImage='/images/header_for_winner_modal.png' :prize='2')
    GameContentWithSidebar
      template(v-slot:content)
        img(src='/images/this_is_a_time_for_american_heroes_and_we_reach_for_the_stars.png')
      template(v-slot:footer)
        h1.fragment This is a time for American heroes and we reach for the stars.
    ChooseWinner(headerImage='/images/header_for_winner_modal.png' :prize='2')
    GameContentWithSidebar
      template(v-slot:content)
        img(src='/images/this_guys_walkin_down_a_street_when_he_falls_into_a_hole_the_Walls_are_so_steep_he_cant_get_out.png')
      template(v-slot:footer)
        h1.fragment This guy's walkin' down a street when he falls into a hole. The walls are so steep he can't get out.
    ChooseWinner(headerImage='/images/header_for_winner_modal.png' :prize='2')
    GameContentWithSidebar
      template(v-slot:content)
        img(src='/images/its_not_the_battles_we_lose_that_bother_me_its_the_ones_we_dont_suit_up_for.png')
      template(v-slot:footer)
        h1.fragment It's not the battles we lose that bother me, it's the ones we don't suit up for.
    ChooseWinner(headerImage='/images/header_for_winner_modal.png' :prize='2')
    GameContentWithSidebar
      template(v-slot:content)
        img(src='/images/i_will_wait_in_the_tall_grass_for_you_senator.png')
      template(v-slot:footer)
        h1.fragment I will wait in the tall grass for you, Senator.
    ChooseWinner(headerImage='/images/header_for_winner_modal.png' :prize='2')
    GameContentWithSidebar
      template(v-slot:content)
        img(src='/images/if_you_were_in_an_accident_i_wouldnt_stop_for_red_lights.png')
      template(v-slot:footer)
        h1.fragment If you were in an accident I wouldn't stop for red lights.
    ChooseWinner(headerImage='/images/header_for_winner_modal.png' :prize='2')
    PlayerBoard
    PlayerBoard
    Slide(class='darkgray')
      h2.text-white Album Titles
    GameContentWithSidebar
      template(v-slot:content)
        img(src='/images/recovering_the_satellites.png')
      template(v-slot:footer)
        h1.fragment Recovering the Satellites by Counting Crows
    ChooseWinner(headerImage='/images/header_for_winner_modal.png' :prize='3')
    GameContentWithSidebar
      template(v-slot:content)
        img(src='/images/houses_of_the_holy.png')
      template(v-slot:footer)
        h1.fragment Houses of the Holy by Led Zeppelin
    ChooseWinner(headerImage='/images/header_for_winner_modal.png' :prize='3')
    GameContentWithSidebar
      template(v-slot:content)
        img(src='/images/ropin_the_wind.png')
      template(v-slot:footer)
        h1.fragment Ropin' the Wind by Garth Brooks
    ChooseWinner(headerImage='/images/header_for_winner_modal.png' :prize='3')
    GameContentWithSidebar
      template(v-slot:content)
        img(src='/images/sgt_peppers_lonely_hearts_club_band.png')
      template(v-slot:footer)
        h1.fragment Sgt. Pepper's Lonely Hearts Club Band by The Beatles
    ChooseWinner(headerImage='/images/header_for_winner_modal.png' :prize='3')
    GameContentWithSidebar
      template(v-slot:content)
        img(src='/images/that_much_further_west.png')
      template(v-slot:footer)
        h1.fragment That Much Further West by Lucero
    ChooseWinner(headerImage='/images/header_for_winner_modal.png' :prize='3')
    GameContentWithSidebar
      template(v-slot:content)
        img(src='/images/grave_dancers_union.png')
      template(v-slot:footer)
        h1.fragment Grave Dancers Union by Soul Asylum
    ChooseWinner(headerImage='/images/header_for_winner_modal.png' :prize='3')
    PlayerBoard
</template>

<script>
import BackgroundImageSlide from '@/components/base/BackgroundImageSlide.vue'
import Reveal from '@/components/base/Reveal.vue'
import Title from '@/components/base/Title.vue'
import Slide from '@/components/base/Slide.vue'
import VideoSlide from '@/components/base/VideoSlide.vue'
import ActionButton from '@/components/base/ActionButton.vue'
import GameVideo from '@/components/base/GameVideo.vue'

import PlayerBoard from '@/components/Players/PlayerBoard.vue'

import GameContentWithSidebar from '@/components/base/GameContentWithSidebar.vue'
import ChooseWinner from '@/components/Players/ChooseWinner.vue'

export default {
  name: 'Home',
  components: {
    PlayerBoard,
    Title,
    Slide,
    Reveal,
    BackgroundImageSlide,
    VideoSlide,
    ActionButton,
    GameVideo,
    ChooseWinner,
    GameContentWithSidebar
  }
}
</script>

<style lang='scss'>
html {
  font-size: 36px;
}
</style>
